; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes --force-update
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cheri-csub.ll
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - | FileCheck %s --check-prefix=PURECAP

define i64 @subp(i8 addrspace(200)* readnone %a, i8 addrspace(200)* readnone %b) nounwind {
; HYBRID-LABEL: subp:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    gcvalue x8, c1
; HYBRID-NEXT:    gcvalue x9, c0
; HYBRID-NEXT:    sub x0, x9, x8
; HYBRID-NEXT:    ret
;
; PURECAP-LABEL: subp:
; PURECAP:       .Lfunc_begin0:
; PURECAP-NEXT:  // %bb.0: // %entry
; PURECAP-NEXT:    gcvalue x8, c1
; PURECAP-NEXT:    gcvalue x9, c0
; PURECAP-NEXT:    sub x0, x9, x8
; PURECAP-NEXT:    ret c30
entry:
  %0 = tail call i64 @llvm.cheri.cap.diff.i64(i8 addrspace(200)* %a, i8 addrspace(200)* %b)
  ret i64 %0
}

declare i64 @llvm.cheri.cap.diff.i64(i8 addrspace(200)*, i8 addrspace(200)*)
