; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes --force-update
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/dagcombine-ptradd-deleted-regression.ll
; This would previously crash DAGCombiner::visitPTRADD since the PTRADD
; corresponding to the second GEP would be collapsed to a no-op when
; reassociated and delete the synthesised PTRADD node, not just the ADD, which
; the folding code was not prepared for.
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - | FileCheck %s --check-prefix=PURECAP

declare i32 @bar(i32 addrspace(200)*)

define internal i32 @foo(i32 addrspace(200)* %a, i64 addrspace(200)* %b) nounwind {
; HYBRID-LABEL: foo:
; HYBRID:       // %bb.0: // %entry
; HYBRID-NEXT:    sub sp, sp, #32
; HYBRID-NEXT:    add c0, c0, #4
; HYBRID-NEXT:    str x30, [sp, #16] // 8-byte Folded Spill
; HYBRID-NEXT:    str c0, [sp, #0] // 16-byte Folded Spill
; HYBRID-NEXT:  .LBB0_1: // %loop
; HYBRID-NEXT:    // =>This Inner Loop Header: Depth=1
; HYBRID-NEXT:    ldr c0, [sp, #0] // 16-byte Folded Reload
; HYBRID-NEXT:    bl bar
; HYBRID-NEXT:    b .LBB0_1
;
; PURECAP-LABEL: foo:
; PURECAP:       .Lfunc_begin0:
; PURECAP-NEXT:  // %bb.0: // %entry
; PURECAP-NEXT:    stp c30, c19, [csp, #-32]! // 32-byte Folded Spill
; PURECAP-NEXT:    add c19, c0, #4
; PURECAP-NEXT:  .LBB0_1: // %loop
; PURECAP-NEXT:    // =>This Inner Loop Header: Depth=1
; PURECAP-NEXT:    mov c0, c19
; PURECAP-NEXT:    bl bar
; PURECAP-NEXT:    b .LBB0_1
entry:
  br label %loop

loop:
  %0 = getelementptr inbounds i32, i32 addrspace(200)* %a, i64 1
  %1 = load i64, i64 addrspace(200)* %b, align 16
  %2 = mul i64 0, %1
  %3 = getelementptr inbounds i32, i32 addrspace(200)* %0, i64 %2
  %4 = call i32 @bar(i32 addrspace(200)* %3)
  br label %loop
}
