; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes --force-update
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/trunc-load.ll
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi purecap -mattr=+morello,+c64 %s -o - < %s | FileCheck %s --check-prefix=PURECAP
; RUN: llc -mtriple=aarch64 --relocation-model=pic -target-abi aapcs -mattr=+morello,-c64 -o - < %s | FileCheck %s --check-prefix=HYBRID

define zeroext i16 @trunc_load_zext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_load_zext:
; PURECAP:       .Lfunc_begin0:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0:
; PURECAP-NEXT:    ldrh w0, [c0]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: trunc_load_zext:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    ldurh w0, [c0, #0]
; HYBRID-NEXT:    ret
  %1 = load i32, i32 addrspace(200)* %p
  %2 = trunc i32 %1 to i16
  ret i16 %2
}

define signext i16 @trunc_load_sext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_load_sext:
; PURECAP:       .Lfunc_begin1:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0:
; PURECAP-NEXT:    ldrsh w0, [c0]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: trunc_load_sext:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    ldursh w0, [c0, #0]
; HYBRID-NEXT:    ret
  %1 = load i32, i32 addrspace(200)* %p
  %2 = trunc i32 %1 to i16
  ret i16 %2
}

define zeroext i16 @trunc_load_gep_zext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_load_gep_zext:
; PURECAP:       .Lfunc_begin2:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0:
; PURECAP-NEXT:    ldrh w0, [c0, #4]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: trunc_load_gep_zext:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    ldurh w0, [c0, #4]
; HYBRID-NEXT:    ret
  %1 = getelementptr i32, i32 addrspace(200)* %p, i64 1
  %2 = load i32, i32 addrspace(200)* %1
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define signext i16 @trunc_load_gep_sext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_load_gep_sext:
; PURECAP:       .Lfunc_begin3:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0:
; PURECAP-NEXT:    ldrsh w0, [c0, #4]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: trunc_load_gep_sext:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    ldursh w0, [c0, #4]
; HYBRID-NEXT:    ret
  %1 = getelementptr i32, i32 addrspace(200)* %p, i64 1
  %2 = load i32, i32 addrspace(200)* %1
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define zeroext i16 @trunc_lshr_load_zext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_lshr_load_zext:
; PURECAP:       .Lfunc_begin4:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0:
; PURECAP-NEXT:    ldrh w0, [c0, #2]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: trunc_lshr_load_zext:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    ldurh w0, [c0, #2]
; HYBRID-NEXT:    ret
  %1 = load i32, i32 addrspace(200)* %p
  %2 = lshr i32 %1, 16
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define signext i16 @trunc_lshr_load_sext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_lshr_load_sext:
; PURECAP:       .Lfunc_begin5:
; PURECAP-NEXT:    .cfi_startproc purecap
; PURECAP-NEXT:  // %bb.0:
; PURECAP-NEXT:    ldrsh w0, [c0, #2]
; PURECAP-NEXT:    ret c30
;
; HYBRID-LABEL: trunc_lshr_load_sext:
; HYBRID:       // %bb.0:
; HYBRID-NEXT:    ldursh w0, [c0, #2]
; HYBRID-NEXT:    ret
  %1 = load i32, i32 addrspace(200)* %p
  %2 = lshr i32 %1, 16
  %3 = trunc i32 %2 to i16
  ret i16 %3
}
