; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-none-elf < %s -mattr=+c64,+morello -target-abi purecap | FileCheck %s

@a = addrspace(200) global i32 0, align 4
@b = addrspace(200) constant i64 ptrtoint (i32 addrspace(200)* @a to i64), align 8

define i32 @f() addrspace(200) #0 {
; CHECK-LABEL: f:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    adrp c0, :got:a
; CHECK-NEXT:    ldr c0, [c0, :got_lo12:a]
; CHECK-NEXT:    gcvalue x0, c0
; CHECK-NEXT:    // kill: def $w0 killed $w0 killed $x0
; CHECK-NEXT:    ret c30
entry:
  ret i32 ptrtoint (i32 addrspace(200)* @a to i32)
}
