; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=arm64-none-linux-gnu -mattr=+morello,+c64 -target-abi purecap -verify-machineinstrs < %s | FileCheck %s

@initial_exec_var = external thread_local(initialexec) addrspace(200) global i32

define i32 @test_initial_exec() addrspace(200) {
; CHECK-LABEL: test_initial_exec:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    adrp c0, :gottprel:initial_exec_var
; CHECK-NEXT:    add c0, c0, :gottprel_lo12:initial_exec_var
; CHECK-NEXT:    ldp x0, x8, [c0]
; CHECK-NEXT:    mrs c1, CTPIDR_EL0
; CHECK-NEXT:    add c0, c1, x0, uxtx
; CHECK-NEXT:    scbnds c0, c0, x8
; CHECK-NEXT:    ldr w0, [c0]
; CHECK-NEXT:    ret c30
  %val = load i32, i32 addrspace(200)* @initial_exec_var
  ret i32 %val
}

define i32 addrspace(200)* @test_initial_exec_addr() addrspace(200) {
; CHECK-LABEL: test_initial_exec_addr:
; CHECK:       .Lfunc_begin1:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    adrp c0, :gottprel:initial_exec_var
; CHECK-NEXT:    add c0, c0, :gottprel_lo12:initial_exec_var
; CHECK-NEXT:    ldp x0, x8, [c0]
; CHECK-NEXT:    mrs c1, CTPIDR_EL0
; CHECK-NEXT:    add c0, c1, x0, uxtx
; CHECK-NEXT:    scbnds c0, c0, x8
; CHECK-NEXT:    ret c30
  ret i32 addrspace(200)* @initial_exec_var
}
