; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=aarch64 -mattr=+morello -o - %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-none-unknown-elf"

%struct.__va_list = type { i8*, i8*, i8*, i32, i32 }

; Capabilities are passed indirectly so we don't need to spill any capability
; registers.

define dso_local void @test_varargs(%struct.__va_list* noalias sret(%struct.__va_list) align 8 %agg.result, i32 %count, ...) local_unnamed_addr #0 {
; CHECK-LABEL: test_varargs:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    sub sp, sp, #224
; CHECK-NEXT:    add x9, sp, #136
; CHECK-NEXT:    mov x11, #-56
; CHECK-NEXT:    mov x12, sp
; CHECK-NEXT:    add x9, x9, #56
; CHECK-NEXT:    add x10, sp, #224
; CHECK-NEXT:    movk x11, #65408, lsl #32
; CHECK-NEXT:    add x12, x12, #128
; CHECK-NEXT:    stp q0, q1, [sp]
; CHECK-NEXT:    stp x3, x4, [sp, #152]
; CHECK-NEXT:    stp x7, x10, [sp, #184]
; CHECK-NEXT:    stp x9, x12, [sp, #200]
; CHECK-NEXT:    str x11, [sp, #216]
; CHECK-NEXT:    ldp q0, q1, [sp, #192]
; CHECK-NEXT:    stp x1, x2, [sp, #136]
; CHECK-NEXT:    stp x5, x6, [sp, #168]
; CHECK-NEXT:    stp q2, q3, [sp, #32]
; CHECK-NEXT:    stp q4, q5, [sp, #64]
; CHECK-NEXT:    stp q6, q7, [sp, #96]
; CHECK-NEXT:    stp q0, q1, [x8]
; CHECK-NEXT:    add sp, sp, #224
; CHECK-NEXT:    ret
entry:
  %args = alloca %struct.__va_list, align 8
  %0 = bitcast %struct.__va_list* %args to i8*
  call void @llvm.lifetime.start.p0i8(i64 32, i8* nonnull %0) #0
  call void @llvm.va_start.p0i8(i8* nonnull %0)
  %1 = bitcast %struct.__va_list* %agg.result to i8*
  call void @llvm.va_copy.p0i8.p0i8(i8* %1, i8* nonnull %0)
  call void @llvm.lifetime.end.p0i8(i64 32, i8* nonnull %0) #0
  ret void
}

declare void @llvm.va_copy.p0i8.p0i8(i8*, i8*) #0
declare void @llvm.va_start.p0i8(i8*) #0
declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #0
declare void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #0

attributes #0 = { nounwind }
