; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -march=aarch64 -mattr=+c64,+morello -target-abi purecap -mcpu=rainier -o - | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "aarch64-none-unknown-elf"

; Don't crash while building/scalarizing fat pointer vectors.

define void @foo() local_unnamed_addr addrspace(200) align 2 {
; CHECK-LABEL: foo:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:    .cfi_startproc purecap
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    sub csp, csp, #16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    cmp xzr, x8
; CHECK-NEXT:    cset w8, hi
; CHECK-NEXT:    sbfx x8, x8, #0, #1
; CHECK-NEXT:    dup v0.2d, x8
; CHECK-NEXT:    fmov w8, s0
; CHECK-NEXT:    and w9, w8, #0x1
; CHECK-NEXT:    lsl w10, w9, #1
; CHECK-NEXT:    sub w8, w10, w8
; CHECK-NEXT:    orr w8, w8, w9, lsl #2
; CHECK-NEXT:    orr w8, w8, w9, lsl #3
; CHECK-NEXT:    and w8, w8, #0xf
; CHECK-NEXT:    cmp w8, #0
; CHECK-NEXT:    ccmp wzr, #0, #0, eq
; CHECK-NEXT:    ccmp wzr, #0, #0, eq
; CHECK-NEXT:    b.eq .LBB0_2
; CHECK-NEXT:  // %bb.1: // %for.body21.preheader180
; CHECK-NEXT:    add csp, csp, #16
; CHECK-NEXT:    ret c30
; CHECK-NEXT:    .p2align 5, 0x0, 16
; CHECK-NEXT:  .LBB0_2: // %vector.body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    b .LBB0_2
entry:
  %0 = icmp ugt <4 x i8 addrspace(200)*> zeroinitializer, undef
  %1 = insertelement <2 x i8 addrspace(200)*> poison, i8 addrspace(200)* null, i32 0
  %2 = insertelement <2 x i8 addrspace(200)*> %1, i8 addrspace(200)* undef, i32 1
  %shuffle179 = shufflevector <2 x i8 addrspace(200)*> %2, <2 x i8 addrspace(200)*> poison, <4 x i32> <i32 0, i32 0, i32 0, i32 1>
  %3 = icmp ugt <4 x i8 addrspace(200)*> %shuffle179, undef
  %4 = and <4 x i1> %0, %3
  %5 = bitcast <4 x i1> %4 to i4
  %6 = icmp ne i4 %5, 0
  %7 = or i1 %6, undef
  %8 = or i1 %7, undef
  br i1 %8, label %for.body21.preheader180, label %vector.body

vector.body:                                      ; preds = %vector.body, %entry
  br label %vector.body

for.body21.preheader180:                          ; preds = %entry
  ret void
}
