; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=aarch64 -mattr=+morello -o - %s | FileCheck %s

target datalayout = "e-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-none-unknown-elf"

define dso_local i32 @foo(i32 addrspace(200)* %p) local_unnamed_addr {
; CHECK-LABEL: foo:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    //APP
; CHECK-NEXT:    ldur w0, [c0, #0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 asm sideeffect "ldr ${0:w}, $1", "=r,*Q"(i32 addrspace(200)* elementtype(i32) %p)
  ret i32 %0
}

define dso_local i32 @bar(i32 addrspace(200)* %p) local_unnamed_addr {
; CHECK-LABEL: bar:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    //APP
; CHECK-NEXT:    ldur w0, [c0, #0]
; CHECK-NEXT:    //NO_APP
; CHECK-NEXT:    ret
entry:
  %0 = tail call i32 asm sideeffect "ldr ${0:w}, $1", "=r,*m"(i32 addrspace(200)* elementtype(i32) %p)
  ret i32 %0
}

